<h1>Meu primeiro sofrimento no Magento T.T</h1>

<table class="table table-striped table-hover mt-4">
        <thead class="table-dark">
            <tr>
                <th>#ID</th>
                <th>Nome</th>
                <th>Email</th>
            </tr>
        </thead>
        <tbody>
            <?php
                foreach ($block->getDados() as $item){
                    echo "
                    <tr>
                        <td>{$item['id']}</td>
                        <td>{$item['author_name']}</td>
                        <td>{$item['email']}</td>
                    </tr>";
                }
            ?>
        </tbody>
</table>








